const languages = [
    {
       "value":"az",
       "text":"Азербайджанский"
    },
    {
       "value":"sq",
       "text":"Албанский"
    },
    {
       "value":"am",
       "text":"Амхарский"
    },
    {
       "value":"en",
       "text":"Английский"
    },
    {
       "value":"ar",
       "text":"Арабский"
    },
    {
       "value":"hy",
       "text":"Армянский"
    },
    {
       "value":"af",
       "text":"Африкаанс"
    },
    {
       "value":"eu",
       "text":"Баскский"
    },
    {
       "value":"ba",
       "text":"Башкирский"
    },
    {
       "value":"be",
       "text":"Белорусский"
    },
    {
       "value":"bn",
       "text":"Бенгальский"
    },
    {
       "value":"my",
       "text":"Бирманский"
    },
    {
       "value":"bg",
       "text":"Болгарский"
    },
    {
       "value":"bs",
       "text":"Боснийский"
    },
    {
       "value":"cy",
       "text":"Валлийский"
    },
    {
       "value":"hu",
       "text":"Венгерский"
    },
    {
       "value":"vi",
       "text":"Вьетнамский"
    },
    {
       "value":"ht",
       "text":"Гаитянский"
    },
    {
       "value":"gl",
       "text":"Галисийский"
    },
    {
       "value":"mrj",
       "text":"Горномарийский"
    },
    {
       "value":"el",
       "text":"Греческий"
    },
    {
       "value":"ka",
       "text":"Грузинский"
    },
    {
       "value":"gu",
       "text":"Гуджарати"
    },
    {
       "value":"da",
       "text":"Датский"
    },
    {
       "value":"he",
       "text":"Иврит"
    },
    {
       "value":"yi",
       "text":"Идиш"
    },
    {
       "value":"id",
       "text":"Индонезийский"
    },
    {
       "value":"ga",
       "text":"Ирландский"
    },
    {
       "value":"is",
       "text":"Исландский"
    },
    {
       "value":"es",
       "text":"Испанский"
    },
    {
       "value":"it",
       "text":"Итальянский"
    },
    {
       "value":"kk",
       "text":"Казахский"
    },
    {
       "value":"kn",
       "text":"Каннада"
    },
    {
       "value":"ca",
       "text":"Каталанский"
    },
    {
       "value":"ky",
       "text":"Киргизский"
    },
    {
       "value":"zh",
       "text":"Китайский"
    },
    {
       "value":"ko",
       "text":"Корейский"
    },
    {
       "value":"xh",
       "text":"Коса"
    },
    {
       "value":"km",
       "text":"Кхмерский"
    },
    {
       "value":"lo",
       "text":"Лаосский"
    },
    {
       "value":"la",
       "text":"Латынь"
    },
    {
       "value":"lv",
       "text":"Латышский"
    },
    {
       "value":"lt",
       "text":"Литовский"
    },
    {
       "value":"lb",
       "text":"Люксембургский"
    },
    {
       "value":"mk",
       "text":"Македонский"
    },
    {
       "value":"mg",
       "text":"Малагасийский"
    },
    {
       "value":"ms",
       "text":"Малайский"
    },
    {
       "value":"ml",
       "text":"Малаялам"
    },
    {
       "value":"mt",
       "text":"Мальтийский"
    },
    {
       "value":"mi",
       "text":"Маори"
    },
    {
       "value":"mr",
       "text":"Маратхи"
    },
    {
       "value":"mhr",
       "text":"Марийский"
    },
    {
       "value":"mn",
       "text":"Монгольский"
    },
    {
       "value":"de",
       "text":"Немецкий"
    },
    {
       "value":"ne",
       "text":"Непальский"
    },
    {
       "value":"nl",
       "text":"Нидерландский"
    },
    {
       "value":"no",
       "text":"Норвежский"
    },
    {
       "value":"pa",
       "text":"Панджаби"
    },
    {
       "value":"pap",
       "text":"Папьяменто"
    },
    {
       "value":"fa",
       "text":"Персидский"
    },
    {
       "value":"pl",
       "text":"Польский"
    },
    {
       "value":"pt",
       "text":"Португальский"
    },
    {
       "value":"ro",
       "text":"Румынский"
    },
    {
       "value":"ru",
       "text":"Русский"
    },
    {
       "value":"ceb",
       "text":"Себуанский"
    },
    {
       "value":"sr",
       "text":"Сербский"
    },
    {
       "value":"si",
       "text":"Сингальский"
    },
    {
       "value":"sk",
       "text":"Словацкий"
    },
    {
       "value":"sl",
       "text":"Словенский"
    },
    {
       "value":"sw",
       "text":"Суахили"
    },
    {
       "value":"su",
       "text":"Сунданский"
    },
    {
       "value":"tl",
       "text":"Тагальский"
    },
    {
       "value":"tg",
       "text":"Таджикский"
    },
    {
       "value":"th",
       "text":"Тайский"
    },
    {
       "value":"ta",
       "text":"Тамильский"
    },
    {
       "value":"tt",
       "text":"Татарский"
    },
    {
       "value":"te",
       "text":"Телугу"
    },
    {
       "value":"tr",
       "text":"Турецкий"
    },
    {
       "value":"udm",
       "text":"Удмуртский"
    },
    {
       "value":"uz",
       "text":"Узбекский"
    },
    {
       "value":"uk",
       "text":"Украинский"
    },
    {
       "value":"ur",
       "text":"Урду"
    },
    {
       "value":"fi",
       "text":"Финский"
    },
    {
       "value":"fr",
       "text":"Французский"
    },
    {
       "value":"hi",
       "text":"Хинди"
    },
    {
       "value":"hr",
       "text":"Хорватский"
    },
    {
       "value":"cs",
       "text":"Чешский"
    },
    {
       "value":"sv",
       "text":"Шведский"
    },
    {
       "value":"gd",
       "text":"Шотландский (гэльский)"
    },
    {
       "value":"sjn",
       "text":"Эльфийский (синдарин)"
    },
    {
       "value":"emj",
       "text":"Эмодзи"
    },
    {
       "value":"eo",
       "text":"Эсперанто"
    },
    {
       "value":"et",
       "text":"Эстонский"
    },
    {
       "value":"jv",
       "text":"Яванский"
    },
    {
       "value":"ja",
       "text":"Японский"
    }
 ]

 export default languages